/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.estacionamento.apresentacao;

import br.univates.estacionamento.main.Sistema;
import br.univates.system32.db.DataBaseException;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author joaoh
 */
public class TelaAdmin extends javax.swing.JFrame
{
    private TelaAdmin telaAdmin;
    private TelaMenu telaMenu;
    private TelaRelatoriosPessoas relatorioPessoa;
    private TelaRelatoriosVeiculos relatorioVeiculo;
    
    public TelaAdmin()
    {
        this.relatorioPessoa  = relatorioPessoa;
        this.relatorioVeiculo = relatorioVeiculo;
        initComponents();
    }
    
    public void setTelaAdmin(TelaAdmin telaAdmin)
    {
        this.telaAdmin = telaAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botaoFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botaoListarPessoas = new javax.swing.JButton();
        botaoListarCarros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoRelatorioPessoas = new javax.swing.JButton();
        botaoRelatorioVeiculos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Administração");
        setName("Tela de Administração"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        botaoFechar.setBackground(new java.awt.Color(204, 204, 204));
        botaoFechar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        botaoFechar.setText("Fechar");
        botaoFechar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        botaoListarPessoas.setBackground(new java.awt.Color(204, 204, 204));
        botaoListarPessoas.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        botaoListarPessoas.setText("Listagem de Pessoas");
        botaoListarPessoas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoListarPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarPessoasActionPerformed(evt);
            }
        });

        botaoListarCarros.setBackground(new java.awt.Color(204, 204, 204));
        botaoListarCarros.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        botaoListarCarros.setText("Listagem de Carros");
        botaoListarCarros.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoListarCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarCarrosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Relatórios");

        botaoRelatorioPessoas.setBackground(new java.awt.Color(204, 204, 204));
        botaoRelatorioPessoas.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        botaoRelatorioPessoas.setText("Filtrar Pessoas");
        botaoRelatorioPessoas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoRelatorioPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRelatorioPessoasActionPerformed(evt);
            }
        });

        botaoRelatorioVeiculos.setBackground(new java.awt.Color(204, 204, 204));
        botaoRelatorioVeiculos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        botaoRelatorioVeiculos.setText("Filtrar Veículos");
        botaoRelatorioVeiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoRelatorioVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRelatorioVeiculosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Relatórios com Filtragens");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoListarCarros)
                            .addComponent(botaoListarPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoRelatorioPessoas)
                            .addComponent(botaoRelatorioVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoListarCarros, botaoListarPessoas, botaoRelatorioPessoas, botaoRelatorioVeiculos});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoListarPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRelatorioPessoas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoListarCarros)
                    .addComponent(botaoRelatorioVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoListarCarros, botaoListarPessoas, botaoRelatorioPessoas, botaoRelatorioVeiculos});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
       dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaoListarPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarPessoasActionPerformed
        Connection connection = null;
        try
        {
            // Obtém a conexão com o banco de dados
            connection = Sistema.getInstance().getDataBaseManager().getConnection();
        
            // Compilar o relatório do formato XML gerando um objeto JasperReport
            JasperReport report = JasperCompileManager.compileReport(getClass().getResourceAsStream("/br/univates/estacionamento/resources/reports/RelatorioPessoas.jrxml"));

            // Cria uma lista de parâmetros para o relatório
            Map param = new HashMap();

            // Gera o relatório efetivamente
            JasperPrint print = JasperFillManager.fillReport(report, param, connection );

            // Exibir o relatório
            JasperViewer.viewReport(print,false);
        } 
        catch (DataBaseException | JRException ex)
        {
            Logger.getLogger(TelaMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoListarPessoasActionPerformed

    private void botaoListarCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarCarrosActionPerformed
        Connection connection = null;
        try
        {
            // Obtém a conexão com o banco de dados
            connection = Sistema.getInstance().getDataBaseManager().getConnection();
        
            // Compilar o relatório do formato XML gerando um objeto JasperReport
            JasperReport report = JasperCompileManager.compileReport(getClass().getResourceAsStream("/br/univates/estacionamento/resources/reports/RelatorioVeiculos.jrxml"));

            // Cria uma lista de parâmetros para o relatório
            Map param = new HashMap();

            // Gera o relatório efetivamente
            JasperPrint print = JasperFillManager.fillReport(report, param, connection );

            // Exibir o relatório
            JasperViewer.viewReport(print,false);
        } 
        catch (DataBaseException | JRException ex)
        {
            Logger.getLogger(TelaMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoListarCarrosActionPerformed

    private void botaoRelatorioPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRelatorioPessoasActionPerformed
        TelaRelatoriosPessoas rp = new TelaRelatoriosPessoas();
        rp.setTelaAdmin(this);
        this.setVisible(false);
        rp.setVisible(true);
    }//GEN-LAST:event_botaoRelatorioPessoasActionPerformed

    private void botaoRelatorioVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRelatorioVeiculosActionPerformed
        TelaRelatoriosVeiculos rv = new TelaRelatoriosVeiculos();
        rv.setTelaAdmin(this);
        this.setVisible(false);
        rv.setVisible(true);
    }//GEN-LAST:event_botaoRelatorioVeiculosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       dispose();
       telaMenu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoListarCarros;
    private javax.swing.JButton botaoListarPessoas;
    private javax.swing.JButton botaoRelatorioPessoas;
    private javax.swing.JButton botaoRelatorioVeiculos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}