/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.estacionamento.apresentacao;

import br.univates.estacionamento.main.Sistema;
import br.univates.estacionamento.negocio.Movimento;
import br.univates.estacionamento.negocio.Veiculo;
import br.univates.estacionamento.persistencia.BDFactory;
import br.univates.system32.db.DataBaseException;
import br.univates.system32.db.DuplicateKeyException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import br.univates.estacionamento.persistencia.EstacionamentoMovimentoBD;
import br.univates.estacionamento.persistencia.EstacionamentoVeiculoBD;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author joaoh
 */
public class TelaCadastroMovimento extends javax.swing.JFrame
{
    private TelaEstacionamento telaEstacionamento;
    private Movimento movimento;
    private boolean novo;
    private TelaRelatoriosMovimentos telaRelatoriosMovimentos;

    public TelaCadastroMovimento(Movimento data)
    {
        novo = false;
        this.telaRelatoriosMovimentos = telaRelatoriosMovimentos;
        initComponents();
        
        // popular comboBox
        ArrayList<Veiculo> veiculos = new ArrayList();
        try 
        {
            EstacionamentoVeiculoBD bd = BDFactory.newVeiculoBD();
            veiculos = bd.readAll();
            
            this.cbVeiculo.removeAllItems();
            for (Veiculo veiculo: veiculos)
            {
                this.cbVeiculo.addItem(veiculo);
            }
            
        } 
        catch (DataBaseException ex) 
        {
            System.out.println( ex.getMessage() );
        }

        ArrayList<Movimento> movimentos = new ArrayList();
        try 
        {
            EstacionamentoMovimentoBD bd = BDFactory.newMovimentoBD();
            movimentos = bd.readAll();
        } 
        catch (DataBaseException ex) 
        {
            System.out.println( ex.getMessage() );
        }
        
        MovimentosTableModel tm = new MovimentosTableModel(movimentos);
        tabelaCadastroMovimentos.setModel(tm);
        tabelaCadastroMovimentos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        ListSelectionModel selectionModel = tabelaCadastroMovimentos.getSelectionModel();
        selectionModel.addListSelectionListener( new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e)
            { 
                int row = tabelaCadastroMovimentos.getSelectedRow();
                
                if (row >=0)
                {
                    MovimentosTableModel tableModel = (MovimentosTableModel)tabelaCadastroMovimentos.getModel();
                    movimento = tableModel.getMovimentos().get(tabelaCadastroMovimentos.getSelectedRow());
                    campoFormatadoCodigo.setInteger(movimento.getId() );
                    campoFormatadoEntrada.setText(movimento.getDtIni());
                    campoFormatadoSaida.setText(movimento.getDtFim());
                    cbVeiculo.setSelectedItem(movimento.getVeiculo());

                    novo = false;
                }
            }
        } );        
    }

    public void atualizarTabela()
    {
        ArrayList<Movimento> movimentos = new ArrayList();
        try 
        {
            EstacionamentoMovimentoBD bd = BDFactory.newMovimentoBD();
            movimentos = bd.readAll();
        } 
        catch (DataBaseException ex) 
        {
            System.out.println( ex.getMessage() );
        }
        
        MovimentosTableModel tableModel = (MovimentosTableModel)tabelaCadastroMovimentos.getModel();
        
        tableModel.setMovimentos(movimentos);
        tabelaCadastroMovimentos.revalidate();
        tabelaCadastroMovimentos.repaint();
    }
    
    public void setTelaEstacionamento(TelaEstacionamento telaEstacionamento)
    {
        this.telaEstacionamento = telaEstacionamento;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botaoFechar = new javax.swing.JButton();
        campoFormatadoEntrada = new javax.swing.JFormattedTextField();
        campoFormatadoSaida = new javax.swing.JFormattedTextField();
        botaoRegistrarEntrada = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        campoFormatadoCodigo = new br.univates.system32.components.JMyNumberField();
        jLabel2 = new javax.swing.JLabel();
        botaoNovo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botaoDeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCadastroMovimentos = new javax.swing.JTable();
        cbVeiculo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        botaoRelatorioRegistrosFiltros = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Registros");
        setName("Tela de Registros"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        botaoFechar.setBackground(new java.awt.Color(204, 204, 204));
        botaoFechar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoFechar.setText("Fechar");
        botaoFechar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        campoFormatadoEntrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        try {
            campoFormatadoEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoFormatadoEntrada.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        campoFormatadoSaida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        try {
            campoFormatadoSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoFormatadoSaida.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        botaoRegistrarEntrada.setBackground(new java.awt.Color(204, 204, 204));
        botaoRegistrarEntrada.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoRegistrarEntrada.setText("Registrar Entrada/Saída");
        botaoRegistrarEntrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoRegistrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarEntradaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setText("Registros");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        campoFormatadoCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        campoFormatadoCodigo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Código *");

        botaoNovo.setBackground(new java.awt.Color(204, 204, 204));
        botaoNovo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoNovo.setText("Novo");
        botaoNovo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("Registro de Entrada*");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("Registro de Saída *");

        botaoDeletar.setBackground(new java.awt.Color(204, 204, 204));
        botaoDeletar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoDeletar.setText("Deletar");
        botaoDeletar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        tabelaCadastroMovimentos.setBackground(new java.awt.Color(153, 153, 153));
        tabelaCadastroMovimentos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tabelaCadastroMovimentos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tabelaCadastroMovimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Entrada", "Saída", "Placa"
            }
        ));
        jScrollPane1.setViewportView(tabelaCadastroMovimentos);

        cbVeiculo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cbVeiculo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Registros de Placas *");

        botaoRelatorioRegistrosFiltros.setBackground(new java.awt.Color(204, 204, 204));
        botaoRelatorioRegistrosFiltros.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoRelatorioRegistrosFiltros.setText("Registros com Filtros");
        botaoRelatorioRegistrosFiltros.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoRelatorioRegistrosFiltros.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                botaoRelatorioRegistrosFiltrosComponentRemoved(evt);
            }
        });
        botaoRelatorioRegistrosFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRelatorioRegistrosFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoFormatadoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoFormatadoSaida, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoFormatadoEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoRegistrarEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoDeletar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoNovo, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoRelatorioRegistrosFiltros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoDeletar, botaoFechar, botaoNovo, botaoRegistrarEntrada, botaoRelatorioRegistrosFiltros, jButton2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoFormatadoCodigo, campoFormatadoEntrada, campoFormatadoSaida, cbVeiculo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoNovo)
                        .addGap(18, 18, 18)
                        .addComponent(botaoRegistrarEntrada)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoFormatadoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoFormatadoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoFormatadoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoDeletar)
                            .addComponent(jLabel4))))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRelatorioRegistrosFiltros))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoDeletar, botaoFechar, botaoNovo, botaoRegistrarEntrada, botaoRelatorioRegistrosFiltros, jButton2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoFormatadoCodigo, campoFormatadoEntrada, campoFormatadoSaida, cbVeiculo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        telaEstacionamento.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
          dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaoRegistrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarEntradaActionPerformed
        int id               = campoFormatadoCodigo.getInteger();
        String entrada       = campoFormatadoEntrada.getText();
        String saida         = campoFormatadoSaida.getText();
        Veiculo veiculo      = (Veiculo)cbVeiculo.getSelectedItem();
        
        if(!entrada.isBlank() && !saida.isBlank())
        {
            try
            {
                EstacionamentoMovimentoBD bd = BDFactory.newMovimentoBD();
                
                if (novo)
                {
                    movimento = new Movimento(id, entrada, saida, veiculo); 
                    bd.create(movimento);
                    novo = false;
                }
                else
                {
                    movimento.setId(id);
                    movimento.setDtIni(entrada);
                    movimento.setDtFim(saida);
                    movimento.setVeiculo(veiculo);
                    bd.edit(movimento);
                }
            }catch (DuplicateKeyException ex)
            {
                System.out.println("Chave duplicada");
            }
            catch (DataBaseException ex)
            {
                System.out.println( ex.getMessage() );
            }
            atualizarTabela();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente.");
        }
    }//GEN-LAST:event_botaoRegistrarEntradaActionPerformed

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        novo = true;
        campoFormatadoCodigo.setText("");
        campoFormatadoEntrada.setText("");
        campoFormatadoSaida.setText("");
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection connection = null;
        try
        {
            // Obtém a conexão com o banco de dados
            connection = Sistema.getInstance().getDataBaseManager().getConnection();
        
            // Compilar o relatório do formato XML gerando um objeto JasperReport
            JasperReport report = JasperCompileManager.compileReport(getClass().getResourceAsStream("/br/univates/estacionamento/resources/reports/RelatorioRegistros.jrxml"));

            // Cria uma lista de parâmetros para o relatório
            Map param = new HashMap();

            // Gera o relatório efetivamente
            JasperPrint print = JasperFillManager.fillReport(report, param, connection );

            // Exibir o relatório
            JasperViewer.viewReport(print,false);
        } 
        catch (DataBaseException | JRException ex)
        {
            Logger.getLogger(TelaMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        try
        {
            EstacionamentoMovimentoBD bd = BDFactory.newMovimentoBD();
            bd.delete(movimento);
        } 
        catch (DataBaseException ex)
        {
            System.out.println(ex.getMessage());
        }

        atualizarTabela();
    }//GEN-LAST:event_botaoDeletarActionPerformed

    private void botaoRelatorioRegistrosFiltrosComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_botaoRelatorioRegistrosFiltrosComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRelatorioRegistrosFiltrosComponentRemoved

    private void botaoRelatorioRegistrosFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRelatorioRegistrosFiltrosActionPerformed
        TelaRelatoriosMovimentos rm =  new TelaRelatoriosMovimentos();
        rm.setTelaCadastroMovimento(this);
        this.setVisible(false);
        rm.setVisible(true);
    }//GEN-LAST:event_botaoRelatorioRegistrosFiltrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoRegistrarEntrada;
    private javax.swing.JButton botaoRelatorioRegistrosFiltros;
    private br.univates.system32.components.JMyNumberField campoFormatadoCodigo;
    private javax.swing.JFormattedTextField campoFormatadoEntrada;
    private javax.swing.JFormattedTextField campoFormatadoSaida;
    private javax.swing.JComboBox<Veiculo> cbVeiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCadastroMovimentos;
    // End of variables declaration//GEN-END:variables
}
