/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.estacionamento.apresentacao;

import br.univates.estacionamento.negocio.Estacionamento;
import br.univates.estacionamento.negocio.Veiculo;
import br.univates.estacionamento.negocio.Pessoa;
import br.univates.estacionamento.negocio.Usuario;
import br.univates.estacionamento.negocio.Vip;

/**
 *
 * @author joaoh
 */
public class TelaMenu extends javax.swing.JFrame
{
    private Veiculo veiculo;
    private Pessoa pessoa;
    private Usuario usuario; 
    private Estacionamento estacionamento;
    private Vip vip;
    
    public TelaMenu()
    {
        this.pessoa         = pessoa;
        this.veiculo        = veiculo;
        this.usuario        = usuario;
        this.estacionamento = estacionamento;
        this.vip            = vip;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        botaoEstacionamento = new javax.swing.JButton();
        botaoCategoriaVeiculos = new javax.swing.JButton();
        botaoCadastrarPessoa = new javax.swing.JButton();
        botaoAdmin = new javax.swing.JButton();
        botaoFechar = new javax.swing.JButton();
        botaoCadastrarUsuarios = new javax.swing.JButton();
        botaoCadastroVips = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Menu");
        setName("Tela de Menu"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        botaoEstacionamento.setBackground(new java.awt.Color(204, 204, 204));
        botaoEstacionamento.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoEstacionamento.setText("Estacionamento");
        botaoEstacionamento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoEstacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstacionamentoActionPerformed(evt);
            }
        });

        botaoCategoriaVeiculos.setBackground(new java.awt.Color(204, 204, 204));
        botaoCategoriaVeiculos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoCategoriaVeiculos.setText("Cadastrar Veículos");
        botaoCategoriaVeiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoCategoriaVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCategoriaVeiculosActionPerformed(evt);
            }
        });

        botaoCadastrarPessoa.setBackground(new java.awt.Color(204, 204, 204));
        botaoCadastrarPessoa.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoCadastrarPessoa.setText("Cadastrar Clientes");
        botaoCadastrarPessoa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoCadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarPessoaActionPerformed(evt);
            }
        });

        botaoAdmin.setBackground(new java.awt.Color(204, 204, 204));
        botaoAdmin.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoAdmin.setText("Relatórios do Menu");
        botaoAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdminActionPerformed(evt);
            }
        });

        botaoFechar.setBackground(new java.awt.Color(204, 204, 204));
        botaoFechar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoFechar.setText("Fechar");
        botaoFechar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        botaoCadastrarUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        botaoCadastrarUsuarios.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoCadastrarUsuarios.setText("Cadastrar Usuários");
        botaoCadastrarUsuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarUsuariosActionPerformed(evt);
            }
        });

        botaoCadastroVips.setBackground(new java.awt.Color(204, 204, 204));
        botaoCadastroVips.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoCadastroVips.setText("Cadastrar Vips");
        botaoCadastroVips.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoCadastroVips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroVipsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCategoriaVeiculos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoCadastroVips)
                            .addComponent(botaoEstacionamento, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoCadastrarUsuarios)
                            .addComponent(botaoCadastrarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoAdmin, botaoCadastrarPessoa, botaoCadastrarUsuarios, botaoCadastroVips, botaoCategoriaVeiculos, botaoEstacionamento, botaoFechar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCategoriaVeiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCadastrarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCadastrarUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCadastroVips)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEstacionamento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoCadastrarPessoa, botaoCadastrarUsuarios, botaoCadastroVips, botaoCategoriaVeiculos, botaoEstacionamento});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoAdmin, botaoFechar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Tela de Menu");
        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdminActionPerformed
        TelaAdmin ta = new TelaAdmin();
        ta.setTelaAdmin(ta);
        ta.setVisible(true);
    }//GEN-LAST:event_botaoAdminActionPerformed

    private void botaoEstacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstacionamentoActionPerformed
        TelaEstacionamento te = new TelaEstacionamento();
        te.setTelaMenu(this);
        te.setVisible(true);
    }//GEN-LAST:event_botaoEstacionamentoActionPerformed

    private void botaoCadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarPessoaActionPerformed
        TelaCadastroPessoa cp = new TelaCadastroPessoa(pessoa);
        cp.setTelaMenu(this);
        cp.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarPessoaActionPerformed

    private void botaoCategoriaVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCategoriaVeiculosActionPerformed
        TelaCadastroVeiculo ca = new TelaCadastroVeiculo(veiculo);
        ca.setTelaMenu(this);
        ca.setVisible(true);
    }//GEN-LAST:event_botaoCategoriaVeiculosActionPerformed

    private void botaoCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarUsuariosActionPerformed
        TelaCadastroUsuario us = new TelaCadastroUsuario(usuario);
        us.setTelaMenu(this);
        us.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarUsuariosActionPerformed

    private void botaoCadastroVipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroVipsActionPerformed
        TelaCadastroVips v = new TelaCadastroVips(vip);
        v.setTelaMenu(this);
        v.setVisible(true);
    }//GEN-LAST:event_botaoCadastroVipsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdmin;
    private javax.swing.JButton botaoCadastrarPessoa;
    private javax.swing.JButton botaoCadastrarUsuarios;
    private javax.swing.JButton botaoCadastroVips;
    private javax.swing.JButton botaoCategoriaVeiculos;
    private javax.swing.JButton botaoEstacionamento;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
