/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.estacionamento.apresentacao;

import br.univates.estacionamento.negocio.Movimento;
import br.univates.estacionamento.negocio.Pessoa;
import br.univates.system32.db.DataBaseException;
import br.univates.system32.db.DuplicateKeyException;
import br.univates.estacionamento.negocio.Veiculo;
import br.univates.estacionamento.persistencia.BDFactory;
import br.univates.estacionamento.persistencia.EstacionamentoMovimentoBD;
import br.univates.estacionamento.persistencia.EstacionamentoPessoaBD;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import br.univates.estacionamento.persistencia.EstacionamentoVeiculoBD;
import javax.swing.JOptionPane;

/**
 *
 * @author joaoh
 */
public class TelaCadastroVeiculo extends javax.swing.JFrame
{
    private Veiculo veiculo;
    private Movimento movimento;
    private TelaMenu telaMenu;
    private boolean novo;
    
    public TelaCadastroVeiculo(Veiculo v)
    {
        novo = false;
        initComponents();

        // popular comboBox
        ArrayList<Pessoa> pessoas = new ArrayList();
        try 
        {
            EstacionamentoPessoaBD bd = BDFactory.newPessoaBD();
            pessoas = bd.readAll();
            
            this.cbPessoa.removeAllItems();
            for (Pessoa pessoa: pessoas)
            {
                this.cbPessoa.addItem(pessoa);
            }
        } 
        catch (DataBaseException ex) 
        {
            System.out.println( ex.getMessage() );
        }
        
        ArrayList<Veiculo> veiculos = new ArrayList();
        try 
        {
            EstacionamentoVeiculoBD bd = BDFactory.newVeiculoBD();
            veiculos = bd.readAll();
        } 
        catch (DataBaseException ex) 
        {
            System.out.println( ex.getMessage() );
        }
        
        VeiculosTableModel vtm = new VeiculosTableModel(veiculos);
        tabelaCadastroVeiculos.setModel(vtm);
        tabelaCadastroVeiculos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        ListSelectionModel selectionModel = tabelaCadastroVeiculos.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e)
            { 
                int row = tabelaCadastroVeiculos.getSelectedRow();
                
                if (row >=0)
                {
                    VeiculosTableModel tableModel = (VeiculosTableModel)tabelaCadastroVeiculos.getModel();
                    veiculo = tableModel.getVeiculos().get(tabelaCadastroVeiculos.getSelectedRow());
                    campoFormatadoCodigo.setInteger(veiculo.getId() );
                    campoFormatadoPlaca.setText(veiculo.getPlaca());
                    campoFormatadoModelo.setText(veiculo.getModelo());
                    cbPessoa.setSelectedItem(veiculo.getPessoa());
                    novo = false;
                }
            }
        } );
    }
    
    public void atualizarTabela()
    {
        ArrayList<Veiculo> veiculos = new ArrayList();
        try 
        {
            EstacionamentoVeiculoBD bd = BDFactory.newVeiculoBD();
            veiculos = bd.readAll();
        } 
        catch (DataBaseException ex) 
        {
            System.out.println( ex.getMessage() );
        }
        
        VeiculosTableModel tableModel = (VeiculosTableModel)tabelaCadastroVeiculos.getModel();
        
        tableModel.setVeiculos(veiculos);
        tabelaCadastroVeiculos.revalidate();
        tabelaCadastroVeiculos.repaint();
    }
    
    public void setTelaMenu(TelaMenu telaMenu)
    {
        this.telaMenu = telaMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoFechar = new javax.swing.JButton();
        campoFormatadoPlaca = new javax.swing.JFormattedTextField();
        campoFormatadoModelo = new javax.swing.JFormattedTextField();
        botaoDeletar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoNovo = new javax.swing.JButton();
        campoFormatadoCodigo = new br.univates.system32.components.JMyNumberField();
        rotuloPlaca = new javax.swing.JLabel();
        rotuloModelo = new javax.swing.JLabel();
        rotuloCodigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCadastroVeiculos = new javax.swing.JTable();
        cbPessoa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela cadastro de Veículos");
        setBackground(new java.awt.Color(153, 153, 153));
        setName("Tela cadastro de Veículos"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        botaoFechar.setBackground(new java.awt.Color(204, 204, 204));
        botaoFechar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoFechar.setText("Fechar");
        botaoFechar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        campoFormatadoPlaca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        try {
            campoFormatadoPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU#-U##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoFormatadoPlaca.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        campoFormatadoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFormatadoPlacaActionPerformed(evt);
            }
        });

        campoFormatadoModelo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        campoFormatadoModelo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        botaoDeletar.setBackground(new java.awt.Color(204, 204, 204));
        botaoDeletar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoDeletar.setText("Deletar");
        botaoDeletar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        botaoSalvar.setBackground(new java.awt.Color(204, 204, 204));
        botaoSalvar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoNovo.setBackground(new java.awt.Color(204, 204, 204));
        botaoNovo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoNovo.setText("Novo");
        botaoNovo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        campoFormatadoCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        campoFormatadoCodigo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        campoFormatadoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFormatadoCodigoActionPerformed(evt);
            }
        });

        rotuloPlaca.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        rotuloPlaca.setText("Placa*");

        rotuloModelo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        rotuloModelo.setText("Modelo*");

        rotuloCodigo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        rotuloCodigo.setText("Código*");

        tabelaCadastroVeiculos.setBackground(new java.awt.Color(153, 153, 153));
        tabelaCadastroVeiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tabelaCadastroVeiculos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tabelaCadastroVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Placa", "Modelo", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCadastroVeiculos.setToolTipText("");
        tabelaCadastroVeiculos.setGridColor(new java.awt.Color(153, 153, 153));
        tabelaCadastroVeiculos.setName(""); // NOI18N
        jScrollPane1.setViewportView(tabelaCadastroVeiculos);

        cbPessoa.setBackground(new java.awt.Color(204, 204, 204));
        cbPessoa.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cbPessoa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Cliente *");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rotuloModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(campoFormatadoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rotuloPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(campoFormatadoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(rotuloCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoFormatadoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoDeletar, botaoFechar, botaoNovo, botaoSalvar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoFormatadoModelo, campoFormatadoPlaca, cbPessoa});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, rotuloCodigo, rotuloModelo, rotuloPlaca});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFormatadoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotuloCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFormatadoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFormatadoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotuloModelo))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoDeletar)
                    .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, rotuloCodigo, rotuloModelo, rotuloPlaca});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoFormatadoCodigo, campoFormatadoModelo, campoFormatadoPlaca, cbPessoa});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoDeletar, botaoFechar, botaoNovo, botaoSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoFormatadoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFormatadoPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFormatadoPlacaActionPerformed

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        novo = true;
        campoFormatadoCodigo.setText("");
        campoFormatadoPlaca.setText("");
        campoFormatadoModelo.setText("");
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        int id          = campoFormatadoCodigo.getInteger();
        String placa    = campoFormatadoPlaca.getText();
        String modelo   = campoFormatadoModelo.getText();
        Pessoa pessoa   = (Pessoa)cbPessoa.getSelectedItem();
        
        if(!placa.isBlank() && !modelo.isBlank())
        {
            try
            {
                EstacionamentoVeiculoBD bd = BDFactory.newVeiculoBD();
                if (novo)
                {
                    veiculo = new Veiculo(id, placa , modelo, pessoa);
                    bd.create(veiculo);
                    novo = false;
                }
                else
                {
                    veiculo.setId(id);
                    veiculo.setPlaca(placa);
                    veiculo.setModelo(modelo);
                    veiculo.setPessoa(pessoa);
                    bd.edit(veiculo);
                }
            }
            catch (DuplicateKeyException ex)
            {
                System.out.println("Chave duplicada");
            }
            catch (DataBaseException ex)
            {
                System.out.println( ex.getMessage() );
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        }
        
        atualizarTabela();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        try
        {  
            EstacionamentoVeiculoBD dao = BDFactory.newVeiculoBD();
            dao.delete(veiculo);
        } 
        catch (DataBaseException ex)
        {
            System.out.println(ex.getMessage());
        }

        atualizarTabela();
    }//GEN-LAST:event_botaoDeletarActionPerformed

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
       dispose();
       telaMenu.setVisible(true);
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void campoFormatadoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFormatadoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFormatadoCodigoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       dispose();
       telaMenu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoSalvar;
    private br.univates.system32.components.JMyNumberField campoFormatadoCodigo;
    private javax.swing.JFormattedTextField campoFormatadoModelo;
    private javax.swing.JFormattedTextField campoFormatadoPlaca;
    private javax.swing.JComboBox<Pessoa> cbPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotuloCodigo;
    private javax.swing.JLabel rotuloModelo;
    private javax.swing.JLabel rotuloPlaca;
    private javax.swing.JTable tabelaCadastroVeiculos;
    // End of variables declaration//GEN-END:variables
}
